### PR TITLE
Modernize CI

### PR DESCRIPTION
**Pull request by turion**
I noticed some CI deprecation warnings, possibly these could fix it in case you want this change :)

### CODE REVIEW

**Comment by turion** [comment]
Wow. A GHC 8.0.2 bug??

**Comment by turion** [comment]
I have no means to reproduce locally. This is wild. It seems reproducible though: https://github.com/turion/finite-typelits/actions/runs/10007861641

**Comment by turion** [comment]
I'd like to re-trigger the CI on the same commit, but I think I don't have the permissions to do that.

**Comment by turion** [comment]
Turns out I can re-run the jobs on my fork. The GHC bug seems to be reproducible: https://github.com/turion/finite-typelits/actions/runs/10007861641/job/27665358314

**Comment by turion** [comment]
The only change I can fathom has an influence here is that you did `cabal sdist` first and then built everything from there. Possibly it's then related to the line `#include "MachDeps.h"`? No idea.

**Comment by mniip** [comment]
I think that's what `${{ matrix.ghc_version < '8.1' && '--disable-optimization' || '' }}` did in my CI code

**Comment by mniip** [comment]
I'ma be real, I have no idea what dependabot does, or what problem it purports to solve.

Doing sdist as a separate step was borrowed from text's and lens' CI and it aims to detect if a .hs file was added to the repo but not to the `exposed-modules` list in cabal. This may no longer be necessary on a new enough cabal version?

**Comment by turion** [comment]
> I'ma be real, I have no idea what dependabot does, or what problem it purports to solve.

In this configuration it simply bumps the dependencies of used github actions (like `haskell-actions/setup@v2`).

> Doing sdist as a separate step was borrowed from text's and lens' CI and it aims to detect if a .hs file was added to the repo but not to the `exposed-modules` list in cabal. This may no longer be necessary on a new enough cabal version?

If the file is actually imported from another module in `exposed-modules`, there should be a warning, `-Wmissing-home-modules`. If it is not imported anywhere I'm not sure whether there would be an error. Which of the two situations do you want to be protected against?

**Pull request merged**
