### PR TITLE
Support ghc 9.8

### PR DESCRIPTION
**Pull request by turion**

### CODE REVIEW

**Comment by mniip** [comment]
Should this be a new release (c.f. testsuite) or just fixing the upper bounds on hackage?

**Comment by turion** [comment]
Good question, I don't know. For my own libraries I've always released a new minor version, I don't know how the ecosystem (stackage, hackage outdated reports, nixpkgs, ...) reacts to just fixing the bounds.

**Comment by turion** [comment]
I think a revision should work. Can you tell me when you make a new revision so I can re-enable the package on stackage?

**Comment by turion** [comment]
Hi :) I don't want to be a nuisance, but is there any chance you can make that revision? Currently, the latest revision still has `base < 4.19`, which excludes GHC 9.8.

**Comment by mniip** [comment]
Sorry. Thanks for remining me. Made a revision without new release.

**Pull request merged**
